# syntax=docker/dockerfile:1
FROM ubuntu:22.04 as builder

ARG SERVER_URL
ENV SERVER_URL $SERVER_URL

RUN apt update ; apt install -y curl git gnupg2 ; 
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list 
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - 
RUN apt update ; apt install -y yarn nodejs
 
RUN git clone https://github.com/Casraw/spacebarchat-client.git ; cd spacebarchat-client ; git checkout master 
COPY script-frontend.sh spacebarchat-client/script-frontend.sh
RUN cd spacebarchat-client && chmod +x script-frontend.sh &&  sed -i -e 's/\r$//' script-frontend.sh && ./script-frontend.sh && yarn install && yarn build:web

FROM nginx:alpine

COPY --from=builder /spacebarchat-client/web-build/ /usr/share/nginx/html/
