FROM nginx:alpine

RUN apk add --update certbot certbot-nginx curl

COPY nginx.conf /etc/nginx/nginx.conf
COPY spacebar.conf /etc/nginx/sites-enabled/spacebar.conf
VOLUME /etc/nginx/sites-enabled
COPY script.sh .

CMD ["./script.sh"]
